Repository astrolabsoftware/fink-broker, pull requests merged in 2019-09, with the labels that each got.

#249 Issues/248/slack-integration
  .coveragerc
  bin/distribute.py
  bin/fink
  conf/fink.conf
  conf/fink.conf.cluster
  conf/fink.conf.distribution
  conf/fink.conf.travis
  conf/install_hbase.sh
  conf/slack_channels.txt
  fink_broker/parser.py
  fink_broker/slackUtils.py
  requirements.txt
Labels: gsoc19, redistribution

#272 Issues/270/slack
  fink_broker/slackUtils.py
  sonar-project.properties
Labels: slack, sonarqube

#275 Update gitignore
  .gitignore
Labels: code quality, repo
