Repository astrolabsoftware/fink-broker, pull requests merged in 2019-06, with the labels that each got.

#184 Switch from custom HBase sink provider to foreachBatch mechanism
  bin/raw2science.py
  bin/stream2raw.py
  codecov.yml
  python/fink_broker/sparkUtils.py
  web/js/live.js
Labels: apache spark, hbase, structured streaming extension

#186 Issue 185: Add a new tab to the dashboard (xmatch)
  web/about.html
  web/classification.html
  web/history.html
  web/index.html
  web/js/bar.js
  web/live.html
Labels: dashboard

#188 Bump HBase version for the CI to 2.1.5
  conf/install_hbase.sh
Labels: CI, hbase

#191 Repo management: setup and new structure for the python module
  .coveragerc
  .travis.yml
  bin/fink_test
  docs/index.md
  docs/user_guide/howto.md
  fink_broker/__init__.py
  fink_broker/alertProducer.py
  fink_broker/avroUtils.py
  fink_broker/classification.py
  fink_broker/distributionUtils.py
  fink_broker/filters.py
  fink_broker/hbaseUtils.py
  fink_broker/monitoring.py
  fink_broker/parser.py
  fink_broker/sparkUtils.py
  fink_broker/tester.py
  python/__init__.py
  setup.py
  sonar-project.properties
Labels: repo, version

#192 Bump fink version to 0.2.0
  build.sbt
  conf/fink.conf
  conf/fink.conf.cluster
  conf/fink.conf.travis
  docs/release-notes.md
  docs/user_guide/configuration.md
  fink_broker/__init__.py
  libs/fink-broker_2.11-0.2.0.jar
Labels: version

#195 Add the path to the HBase configuration file when running raw2science
  bin/fink
  conf/fink.conf
  conf/fink.conf.cluster
  conf/fink.conf.travis
  docs/user_guide/configuration.md
Labels: configuration, hbase

#202 Issue 198: fix typo in checkstream
  bin/checkstream.py
Labels: bug, dashboard

#201 Add timestamp-based streaming to Alert distribution service
  bin/distribute.py
  bin/distribution_test.py
  bin/fink
  bin/fink_test
  bin/raw2science.py
  conf/fink.conf
  conf/fink.conf.cluster
  conf/fink.conf.travis
  docs/user_guide/streaming-out.md
  fink_broker/distributionUtils.py
  fink_broker/parser.py
  schemas/distribution_schema.avsc
Labels: apache kafka, hbase, redistribution, services

#211 Update gitignore with mgmt files
  .gitignore
Labels: repo
