Repository astrolabsoftware/fink-broker, pull requests merged in 2019-04, with the labels that each got.

#94 Split Spark extra option and Kafka parameters in configuration files
  bin/fink
  conf/fink.conf
  conf/fink.conf.cluster
  conf/fink.conf.travis
  python/fink_broker/sparkUtils.py
Labels: apache kafka, apache spark, configuration

#95 Remove information on IP and topic
  conf/fink.conf
  conf/fink.conf.cluster
  conf/fink.conf.travis
Labels: configuration

#105 Updating path to Spark binary
  .travis.yml
Labels: CI

#107 Test against multiple versions of Apache Spark
  .travis.yml
Labels: CI, apache spark

#108 Switch to encrypted token for SonarQube
  .travis.yml
Labels: CI, sonarqube

#112 Add section in CONTRIBUTING about naming PR branch
  CONTRIBUTING.md
Labels: quality

#114 Updating travis.yml file to allow for user agnostic CI tests
  .travis.yml
Labels: CI, configuration

#115 Updating gitignore
  .gitignore
Labels: configuration

#118 Disable sonar analysis for PR from fork
  .travis.yml
Labels: CI, sonarqube

#120 Fix typo while checking for external PR
  .travis.yml
Labels: CI, sonarqube

#121 Issue 99: Connect to earliest offsets in tests
  bin/fink_test
  conf/fink.conf.travis
Labels: apache kafka, tests

#124 Issues 123: Fix Kafka retention period
  docker/docker-compose-kafka.yml
Labels: apache kafka, simulator

#127 Remove current logo
  README.md
Labels: documentation

#132 Issue 130: print version number from the binary
  bin/fink
Labels: binary

#131 Bump code version to 0.1.1
  bin/fink
  python/fink_broker/__init__.py
Labels: new release
