Repository astrolabsoftware/fink-broker, pull requests merged in 2019-05, with the labels that each got.

#134 Update the README with a new section named Latest News
  README.md
Labels: documentation, repo

#136 update the gitignore to stop tracking .coverage* files
  .gitignore
Labels: repo

#138 adds missing information in the installation section
  docs/index.md
Labels: documentation

#142 Issue 141: PEP8 fix
  bin/archive.py
  bin/classify_fromstream.py
  bin/filter_and_classify.py
  bin/monitor_fromstream.py
  python/fink_broker/__init__.py
  python/fink_broker/alertProducer.py
  python/fink_broker/avroUtils.py
  python/fink_broker/classification.py
  python/fink_broker/monitoring.py
  python/fink_broker/parser.py
  python/fink_broker/sparkUtils.py
  python/fink_broker/tester.py
Labels: code quality

#146 Issue 145: Add database connector
  bin/archive.py
  bin/classify_fromstream.py
  bin/filter_and_classify.py
  bin/monitor_fromstream.py
  python/fink_broker/sparkUtils.py
Labels: apache spark, database

#140 Issue 139: From raw database to science database
  bin/archive.py
  bin/classify_fromstream.py
  bin/filter_and_classify.py
  bin/fink
  bin/fink_test
  bin/monitor_fromstream.py
  python/fink_broker/__init__.py
  python/fink_broker/alertProducer.py
  python/fink_broker/avroUtils.py
  python/fink_broker/classification.py
  python/fink_broker/filters.py
  python/fink_broker/monitoring.py
  python/fink_broker/parser.py
  python/fink_broker/sparkUtils.py
  python/fink_broker/tester.py
Labels: New feature, apache spark, services

#154 Build the raw database before the unit test suite
  bin/fink_test
Labels: CI, tests

#152 Issue 151: hosting the data for the test suite
  .travis.yml
  bin/fink_test
  datasim/697252845015010002.avro
  datasim/697252845015010003.avro
  datasim/697252845015015001.avro
  datasim/697252845015015004.avro
  datasim/697252845015015006.avro
  datasim/697252845015015011.avro
  datasim/697252845015015013.avro
  datasim/697252845015015014.avro
  datasim/697252845115010001.avro
  datasim/697252845115015002.avro
  datasim/697252845115015006.avro
  datasim/697252845115015010.avro
  datasim/697252845115015014.avro
  datasim/697252845115015015.avro
  datasim/697252845215010000.avro
  datasim/697252845215010002.avro
  datasim/697252845215015001.avro
  datasim/697252845215015003.avro
  datasim/697252845315010001.avro
  datasim/697252845515010007.avro
  datasim/697252845515015002.avro
  datasim/697252845615015006.avro
  datasim/697252845615015014.avro
  datasim/697252845715010000.avro
  datasim/697252845715015010.avro
  datasim/697252845815010001.avro
  datasim/697252845815015006.avro
  datasim/697252845815015007.avro
  datasim/697252845815015008.avro
  datasim/697252845815015016.avro
  datasim/697252845915015010.avro
Labels: CI, tests

#98 Interacting with HBase in Spark Structured Streaming (WIP)
  .gitignore
  .travis.yml
  bin/filter_and_classify.py
  bin/fink
  bin/fink_test
  build.sbt
  conf/fink.conf
  conf/fink.conf.cluster
  conf/fink.conf.travis
  datasim/697252845015010002.avro
  datasim/697252845015010003.avro
  datasim/697252845015015001.avro
  datasim/697252845015015004.avro
  datasim/697252845015015006.avro
  datasim/697252845015015011.avro
  datasim/697252845015015013.avro
  datasim/697252845015015014.avro
  datasim/697252845115010001.avro
  datasim/697252845115015002.avro
  datasim/697252845115015006.avro
  datasim/697252845115015010.avro
  datasim/697252845115015014.avro
  datasim/697252845115015015.avro
  datasim/697252845215010000.avro
  datasim/697252845215010002.avro
  datasim/697252845215015001.avro
  datasim/697252845215015003.avro
  datasim/697252845315010001.avro
  datasim/697252845515010007.avro
  datasim/697252845515015002.avro
  datasim/697252845615015006.avro
  datasim/697252845615015014.avro
  datasim/697252845715010000.avro
  datasim/697252845715015010.avro
  datasim/697252845815010001.avro
  datasim/697252845815015006.avro
  datasim/697252845815015007.avro
  datasim/697252845815015008.avro
  datasim/697252845815015016.avro
  datasim/697252845915015010.avro
  libs/fink-broker_2.11-0.1.0.jar
  libs/shc-core-1.1.3-2.4-s_2.11.jar
  project/Dependencies.scala
  project/assembly.sbt
  project/build.properties
  project/plugins.sbt
  python/fink_broker/hbaseUtils.py
  python/fink_broker/sparkUtils.py
  python/fink_broker/tester.py
  schemas/template_schema_ZTF_rawdatabase.parquet
  src/main/scala/com/astrolabsoftware/fink_broker/catalogUtils.scala
  src/main/scala/org/apache/spark/sql/execution/datasources/hbase/HBaseSinkProvider.scala
Labels: apache spark, database, storage, structured streaming extension

#159 Issue 158: flatten DataFrame columns before sending to the science database
  bin/filter_and_classify.py
  python/fink_broker/sparkUtils.py
Labels: database, hbase

#163 modified fink_test to allow any configuration file
  bin/fink_test
Labels: configuration, tests

#169 Issue 167: changing the threshold for coverage (variation)
  codecov.yml
Labels: code quality

#172 Issue 171: re-introduce the monitoring service (checkstream)
  bin/checkstream.py
  bin/fink
  bin/fink_test
  docs/index.md
Labels: missing, services

#173 Documentation updates
  README.md
  bin/checkstream.py
  bin/fink
  bin/fink_test
  docs/index.md
  docs/license.md
  docs/release-notes.md
  docs/user_guide/available-services.md
  docs/user_guide/configuration.md
  docs/user_guide/database.md
  docs/user_guide/howto.md
  docs/user_guide/testing-fink.md
  mkdocs.yml
Labels: documentation

#177 fix minor typo in the documentation
  docs/index.md
  docs/user_guide/howto.md
  docs/user_guide/testing-fink.md
Labels: documentation, gsoc19
