Repository astrolabsoftware/fink-broker, pull requests merged in 2019-07, with the labels that each got.

#214 Issues/213/pep8
  bin/distribute.py
  bin/distribution_test.py
  fink_broker/distributionUtils.py
  fink_broker/filters.py
Labels: code quality

#216 Issue 215: Add level two generic filter
  .travis.yml
  bin/distribute.py
  conf/distribution-rules.xml
  docs/index.md
  docs/user_guide/howto.md
  fink_broker/distributionUtils.py
  fink_broker/filters.py
  schemas/distribution_schema.avsc
  userfilters/levelone.py
  userfilters/leveltwo.py
Labels: apache spark, gsoc19, services

#221 Catch TimeoutError and ConnectionError when doing xmatch with CDS
  fink_broker/classification.py
  userfilters/levelone.py
Labels: apache spark, bug, services

#222 Make optional the use of cross-match in raw2science
  bin/raw2science.py
  fink_broker/filters.py
  userfilters/levelone.py
Labels: services

#227 New service: Fink shell
  bin/fink_shell
  conf/fink.conf.shell
Labels: services

#228 Bump Fink version from 0.2.0 to 0.2.1
  build.sbt
  conf/fink.conf
  conf/fink.conf.cluster
  conf/fink.conf.travis
  fink_broker/__init__.py
  libs/fink-broker_2.11-0.2.1.jar
Labels: new release

#230 Remove unnecessary mkdocs file
  mkdocs.yml
Labels: repo

#238 New Fink command to stop all services
  bin/fink
Labels: binary, services

#240 Move helper first in the argument list for services
  bin/fink
Labels: binary, bug

#243 Add python logger for pyspark
  bin/checkstream.py
  bin/distribute.py
  bin/distribution_test.py
  bin/fink
  bin/raw2science.py
  bin/stream2raw.py
  conf/fink.conf
  conf/fink.conf.cluster
  conf/fink.conf.travis
  fink_broker/filters.py
  fink_broker/loggingUtils.py
  fink_broker/parser.py
  fink_broker/sparkUtils.py
  fink_broker/tester.py
  userfilters/leveltwo.py
Labels: logger

#247 Ship fink_broker and usefilters modules when submitting Spark jobs
  .coveragerc
  bin/fink
  conf/fink.conf
  conf/fink.conf.cluster
  conf/fink.conf.travis
Labels: apache spark, cluster

#231 Issue 224: enable Authentication and Authorization in Alert Redistribution
  .gitignore
  .travis.yml
  bin/distribute.py
  bin/distribution_test.py
  bin/fink
  bin/fink_kafka
  bin/fink_test
  conf/distribution-rules.xml
  conf/fink.conf
  conf/fink.conf.cluster
  conf/fink.conf.distribution
  conf/fink.conf.travis
  conf/fink_kafka.server0.properties
  conf/fink_kafka.server1.properties
  conf/fink_kafka.server2.properties
  conf/fink_kafka_consumer_jaas.conf
  conf/fink_kafka_producer_jaas.conf
  conf/fink_kafka_server_jaas.conf
  fink_broker/distributionUtils.py
  fink_broker/filters.py
  fink_broker/parser.py
  fink_broker/test_files/distribution-rules-sample.xml
  fink_broker/test_files/distribution-rules-test1.xml
  fink_broker/test_files/distribution-rules-test2.xml
  fink_broker/test_files/distribution-rules-test3.xml
  schemas/distribution_schema.avsc
  userfilters/levelone.py
Labels: apache kafka, gsoc19, redistribution

#252 Switch to TRAVIS_REPO_SLUG to allow for pr and push builds
  .travis.yml
Labels: CI, bug, sonarqube

#253 Fix wrong fix introduced in PR 252 on when using sonar in PRs
  .travis.yml
Labels: CI, sonarqube

#257 Push CI notifications to the travis_ci Slack channel
  .travis.yml
Labels: CI, slack

#245 Issue/20/crossmatch
  fink_broker/classification.py
  requirements.txt
  userfilters/levelone.py
Labels: apache spark, services

#259 Issues/258/codesmell
  bin/raw2science.py
  fink_broker/classification.py
  fink_broker/distributionUtils.py
Labels: code quality, sonarqube

#262 xmatch: handle ValueError during xmatch
  fink_broker/classification.py
Labels: bug, services
