Repository astrolabsoftware/fink-broker, pull requests merged in 2023-12, with the labels that each got.

#764 Update code dependencies
  .github/workflows/test.yml
  deps/requirements-science-no-deps.txt
  deps/requirements-science.txt
  deps/requirements-test.txt
  deps/requirements.txt
  fink_broker/science.py
Labels: dependencies

#768 Deploy blazar filter
  bin/distribute.py
  deps/requirements.txt
Labels: redistribution

#761 Run ciux-based CI
  .ciux
  .github/workflows/itest-gha.yml
  .github/workflows/itest-noscience.yml
  .github/workflows/itest.yml
  Dockerfile
  TODO.org
  build.sh
  conf.sh
  deps/jars-urls.txt
  itest/check-results.sh
  itest/clone-fink-alert-simulator.sh
Labels: continuous integration, continuous deployment

#774 SSO index table
  bin/index_sso_resolver.py
Labels: hbase, index table
