Repository astrolabsoftware/fink-broker, pull requests merged in 2023-07, with the labels that each got.

#721 [Hbase] Push data incrementally in science_archival
  bin/science_archival.py
  fink_broker/sparkUtils.py
Labels: hbase

#718 698 k8s create a noscience pipeline
  .github/workflows/itest.yml
  Dockerfile
  build.sh
  conf.sh
  fink_broker/science.py
  itest/itest.sh
Labels: k8s, continuous integration

#725 Bump dependencies
  deps/requirements-science.txt
  deps/requirements.txt
Labels: dependencies

#726 Use schema converter from fink_utils
  bin/distribute.py
  fink_broker/schema_converter.py
  fink_broker/test_schema_converter.py
Labels: cleaning
