Repository astrolabsoftware/fink-broker, pull requests merged in 2024-02, with the labels that each got.

#803 Add crossmatch with the SPICY catalog
  fink_broker/hbaseUtils.py
  fink_broker/science.py
Labels: science

#814 Bump fink-science to 5.7.1, with the memory leak fixed
  deps/requirements-science.txt
  deps/requirements.txt
Labels: science, performance

#815 Push all data at once in science_archival
  bin/science_archival.py
Labels: apache spark, hbase, performance

#801 799 avoid image build when not needed
  .ciux
  .github/workflows/e2e-common.yml
  .github/workflows/e2e-gha.yml
  .github/workflows/e2e-noscience.yml
  .github/workflows/e2e-science.yml
  .github/workflows/e2e.yml
  bin/DEBUG-TMP
  build.sh
  conf.sh
  doc/devel.adoc
  e2e/check-results.sh
  e2e/fink-start.sh
  e2e/finkconfig_noscience/finkctl.yaml
  e2e/kind-config.sh
  e2e/manifests/minio.yaml
  e2e/minio-install.sh
  e2e/strimzi-install.sh
  examples/aliases-fink.zsh
  push-image.sh
Labels: continuous integration, integration tests

#817 Restore per-file push for science archival
  bin/science_archival.py
Labels: hbase
