Repository astrolabsoftware/fink-broker, pull requests merged in 2024-09, with the labels that each got.

#881 Update Fink internal dependencies
  deps/requirements.txt
Labels: dependencies

#884 Add missing argument
  bin/known_tde.py
Labels: bug

#876 Improve ci/cd design
  .ciux
  .github/workflows/e2e-common.yml
  TODO.argocd
  TODO.org
  chart/Chart.yaml
  chart/values-ci-noscience.yaml
  chart/values-ci-science.yaml
  doc/e2e.md
  e2e/argocd.sh
  e2e/check-results.sh
  e2e/finkconfig/finkctl.secret.yaml
  e2e/finkconfig/finkctl.yaml
  e2e/finkconfig_noscience/finkctl.secret.yaml
  e2e/finkconfig_noscience/finkctl.yaml
  e2e/prereq-install.sh
  e2e/wait-fink.sh
Labels: continuous integration, continuous deployment
