Repository astrolabsoftware/fink-broker, pull requests merged in 2024-01, with the labels that each got.

#777 [HBase] update rowkeys for resolvers
  bin/download_tns.py
  bin/index_sso_resolver.py
Labels: hbase, index table

#781 748 add support for argocd
  .ciux
  .github/workflows/itest-gha.yml
  .github/workflows/itest.yml
  TODO.org
  itest/argocd.sh
  itest/fink-start.sh
  itest/finkctl.yaml
  itest/manifests/minio.yaml
  itest/minio-install.sh
Labels: continuous integration, continuous deployment

#797 Use filter for SIMBAD statistics
  bin/daily_stats.py
Labels: statistics

#790 Replace local crossmatch for VSX with a call to Vizier using the CDS xmatch service
  fink_broker/science.py
Labels: science

#796 Improve e2e science, self-hosted test
  .github/workflows/e2e-gha.yml
  .github/workflows/e2e-noscience.yml
  .github/workflows/e2e-science.yml
  .github/workflows/e2e.yml
  TODO.org
  conf.sh
  e2e/argocd.sh
  e2e/check-results.sh
  e2e/fink-start.sh
  e2e/finkconfig/finkctl.secret.yaml
  e2e/finkconfig/finkctl.yaml
  e2e/finkconfig_noscience/finkctl.secret.yaml
  e2e/finkconfig_noscience/finkctl.yaml
  e2e/manifests/minio.yaml
  e2e/minio-install.sh
  e2e/prereq-install.sh
  e2e/run-minikube.sh
  e2e/strimzi-install.sh
  e2e/strimzi-setup.sh
Labels: continuous integration

#792 Cache only required fields when computing statistics
  .github/workflows/test.yml
  bin/daily_stats.py
  conf/fink.conf.dev
Labels: bug, statistics
