Repository astrolabsoftware/fink-broker, pull requests merged in 2025-04, with the labels that each got.

#975 Bump strimzi helm chart to 0.45.0
  .ciux
  .github/workflows/e2e-common.yml
  .github/workflows/e2e-gha.yml
  .github/workflows/e2e-selfhosted-noscience.yml
  .github/workflows/e2e-selfhosted-science.yml
  TODO.latest
  deps/rubin/requirements-science.txt
  deps/ztf/requirements-science.txt
  doc/troubleshoot.md
  e2e/argocd.sh
  e2e/check-results.sh
  e2e/run.sh
Labels: apache kafka, slack

#978 Script cleaning
  bin/ztf/archive_anomaly.py
  bin/ztf/archive_low_state_blazar.py
  bin/ztf/archive_symbiotic_and_cv_stars.py
  conf/ztf/spark_ips
  fink_broker/common/spark_utils.py
  scheduler/README.md
  scheduler/ztf/check_status.sh
  scheduler/ztf/launch_sso_resolver.sh
  scheduler/ztf/launch_ssoft.sh
Labels: cleaning

#980 Update to fink-filters v6
  bin/ztf/archive_anomaly.py
  bin/ztf/archive_dwarf_agn.py
  bin/ztf/archive_hostless.py
  bin/ztf/archive_ia_active_learning.py
  bin/ztf/archive_index.py
  bin/ztf/archive_known_tde.py
  bin/ztf/archive_low_state_blazar.py
  bin/ztf/archive_statistics.py
  bin/ztf/archive_symbiotic_and_cv_stars.py
  bin/ztf/distribute.py
  bin/ztf/push_to_tns.py
  deps/rubin/requirements.txt
  deps/ztf/requirements-science-no-deps.txt
  deps/ztf/requirements.txt
Labels: dependencies

#982 Remove package edition while installing
  .github/workflows/test.yml
  deps/ztf/requirements-science.txt
Labels: dependencies

#985 Hostless filters
  bin/ztf/distribute.py
  deps/rubin/requirements-science.txt
  deps/rubin/requirements.txt
  deps/ztf/requirements-science.txt
  deps/ztf/requirements.txt
  e2e/check-results.sh
Labels: redistribution
