Repository astrolabsoftware/fink-broker, pull requests merged in 2025-02, with the labels that each got.

#950 Update Fink deps to latest
  deps/requirements-science-no-deps.txt
  deps/requirements-science.txt
  deps/requirements.txt
Labels: dependencies

#955 v4 feedback from prod
  README.md
  bin/fink
  bin/fink_db
  bin/ztf/archive_anomaly.py
  chart/templates/spark-fink-distribution.yaml
  chart/values.yaml
  conf/fink_kafka.server0.properties
  conf/fink_kafka.server1.properties
  conf/fink_kafka.server2.properties
  conf/fink_kafka_consumer_jaas.conf
  conf/fink_kafka_server_jaas.conf
  conf/kafka.zookeeper.properties
  conf/ztf/fink.conf.distribution
  conf/ztf/fink.conf.prod
  fink_broker/ztf/parser.py
  scheduler/ztf/launch_stream.sh
Labels: bug

#962 DB: Fix typo in CLI
  .github/workflows/e2e-common.yml
  .github/workflows/linter.yml
  .github/workflows/sonarqube.yml
  .github/workflows/test.yml
  bin/fink_db
Labels: bug, database

#960 Low state blazars
  .github/workflows/e2e-common.yml
  .github/workflows/linter.yml
  .github/workflows/sonarqube.yml
  .github/workflows/test.yml
  bin/fink_db
  bin/ztf/archive_low_state_blazar.py
  deps/requirements-science.txt
  deps/requirements.txt
  fink_broker/ztf/hbase_utils.py
  fink_broker/ztf/science.py
Labels: hbase, redistribution, science

#956 Send JMX metrics to prometheus
  .ciux
  .github/workflows/e2e-common.yml
  Dockerfile
  TODO.931
  TODO.org
  chart/templates/namespace.yaml
  chart/templates/podmonitor.yaml
  chart/templates/spark-fink-distribution.yaml
  chart/templates/spark-fink-raw2science.yaml
  chart/templates/spark-fink-stream2raw.yaml
  chart/values.yaml
  doc/monitor.md
  doc/troubleshoot.md
  e2e/argocd.sh
  e2e/check-results.sh
  e2e/prereq-install.sh
  e2e/run.sh
Labels: monitoring, k8s
